### PR TITLE
Meteor files 2.2.1 fixes + attachment view

### LINKED ISSUE #4629: [Bug] Avatar Image broken for v6.10 and onwards [Docker Engine] [Linux]
### Server Setup Information
* Did you test in newest Wekan?: 
  * Yes, and for versions v6.10+. This doesn't affect v6.09.
* Operating System: 
  * 5.18.14-arch1-1
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): 
  * Docker Engine (Docker, Containerd and Docker-compose)
* Node.js Version: 
  * Using docker, 14.19.0 for v6.10.
* MongoDB Version: 
  * Not relevant. Tested from v4.4 to 5.
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? 
  * Firefox and Chrome.

### Problem description
Custom avatar image is shown as broken after uploading, doesn't matter what types of image.
As far as I tested, this only affects new installations and not instances that are updated from older versions.

image

This could be a Linux only or Arch only issue, in theory it shouldn't but I can't tell.

#### Reproduction Steps
Create a new directory, make sure volumes/bind mounts are not using any existing ones.
Do `sudo docker-compose down -d`
Create account and upload any image as avatar. 

#### Logs
Didn't output any related logs as far as I can tell.

### PR DESCRIPTION
**Pull request by mfilser**
fixes #4629

### CODE REVIEW

**Comment by mfilser** [comment]
fixes #4629

File: models/attachments.js [hunk 1]
```diff
@@ -129,6 +129,9 @@ if (Meteor.isServer) {
 
       const fileObj = Attachments.findOne({_id: fileObjId});
       moveToStorage(fileObj, storageDestination, fileStoreStrategyFactory);
+
+      // since Meteor-Files 2.1.0 the filename is truncated to 28 characters, so rename the file after upload to the right filename back
```
Comment (dr-dimitru) [inline models/attachments.js:144]: @mfilser @xet7 I'm open to have a pass-through option for sanitization. Believe me there are not pleasant and real cases behind this sanitization

Comment (dr-dimitru) [reply models/attachments.js:144]: like an option to overwrite and pass your own `sanitize` method into the *FilesCollection* constructor

Comment (xet7) [reply models/attachments.js:144]: @dr-dimitru 

Yes, it would be very nice. Also new feature for checking uploaded attachments for viruses etc would expect filenames to be sanitized:

https://github.com/wekan/wekan/pull/4637

Comment (xet7) [reply models/attachments.js:144]: There is also WeKan setting to validate attachment by file size and type:

https://github.com/wekan/wekan/pull/4618

Comment (xet7) [reply models/attachments.js:144]: @mfilser 

What do you think, would that `sanitize` method of `FilesCollection` constructor be better?

Comment (mfilser) [reply models/attachments.js:144]: @xet7 @dr-dimitru 
That would be great to have additional options at `config` variable of [FilesCollection constructor](https://github.com/veliovgroup/Meteor-Files/blob/master/docs/constructor.md)

@dr-dimitru 
Thank you very much for your great framework, without it, it would be much more diffucult or impossible to make all this features in Wekan !

**Comment by dr-dimitru** [comment]
@mfilser @xet7 done in [`v2.3.0`](https://github.com/veliovgroup/Meteor-Files/releases/tag/2.3.0)

See example and [recommended usage here](https://github.com/veliovgroup/meteor-files-website/blob/master/imports/server/files.collection.js#L101-L111)

**Comment by mfilser** [comment]
@dr-dimitru 
Thank you very much. I will have a look at it and integrate the new option into Wekan.

**Comment by gerroon** [comment]
@mfilser 

Is this related to this issue as well?  Some users cant see the cover attachments.

https://github.com/wekan/wekan/discussions/4441

**Comment by mfilser** [comment]
@gerroon
Idk, but i assume not.

**Comment by xet7** [comment]
@gerroon 

Attachment view is related to bringing back swipebox, so when clicking attachment bitmap image PNG/JPG/GIF etc, it opens to fullscreen view of bitmap image.

Not seeing attachments is #4644 , it's because some attachment migrations from CollectionFS to Meteor-Files are incomplete, attachments have wrong URLs, so they are not visible. Attachments are still at MongoDB database, and can be viewed with [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup#using-nosqlbooster-closed-source-mongodb-gui-with-wekan-snap-to-edit-mongodb-database).
